config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: 'items#index'
  resources :items do
    collection do
      get 'search_child', defaults: { format: 'json' }
      get 'search_grandchild', defaults: { format: 'json' }
      get 'update_done'
    end
    member do
      get 'select_category_index'
      get 'confirm'
    end
  end

  resources :users
  resources :credit_cards, only: [:index, :new, :create, :destroy, :buy] do
    get 'buy', on: :member
  end
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :category
  belongs_to :seller, class_name: 'User', foreign_key: 'seller_id'
  belongs_to :buyer, class_name: 'User', optional: true, foreign_key: 'buyer_id'

  with_options presence: true do |admin|
    admin.validates :name, length: { maximum: 40 }
    admin.validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
    admin.validates :description, length: { maximum: 1000 }
    admin.validates :condition_id
    admin.validates :shipping_cost_id
    admin.validates :shipping_time_id
    admin.validates :prefecture_id
    admin.validates :seller_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :condition
  belongs_to_active_hash :shipping_cost
  belongs_to_active_hash :shipping_time
  belongs_to_active_hash :prefecture
  # delegate :name, to: :prefecture
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :index_category_set, only: :index
  before_action :set_item, only: [:show, :edit, :update, :destroy, :confirm]
  before_action :show_all_instance, only: [:show, :edit, :update, :destroy]
  before_action :set_card, only: [:confirm]
  before_action :login, except: [:index, :show]

  def index
    @items    = Item.includes(:images).order(created_at: :desc)
    @ladies   = Item.includes(:images).where(category_id: 33..211).order("id DESC")
    @mens     = Item.includes(:images).where(category_id: 226..356).order("id DESC")
    @babies   = Item.includes(:images).where(category_id: 372..490).order("id DESC")
    @interior = Item.includes(:images).where(category_id: 540..633).order("id DESC")
  end

  def new
    if user_signed_in?
      @item = Item.new
      @item.images.new

    else
      redirect_to new_user_session_path
    end
  end

  def create
    @item = Item.new(item_params)
    if item_params[:images_attributes].nil?
      flash.now[:alert] = "更新できませんでした 【画像を１枚以上入れてください】"
      render :new
    else
      if @item.save
        redirect_to root_path
      else
        @item.images.build
        render :new
      end
    end
  end

  def edit
    unless current_user.id == @item.seller_id
      redirect_to '/'
    end
    @image                 = Image.where(item_id: @item)
    gon.imageLength        = @image.length
    @category_parent_array = Category.where(ancestry: nil)
    grandchild             = @item.category
    child                  = grandchild.parent

    @parent_array = []
    @parent_array << @item.category.parent.parent.name
    @parent_array << @item.category.parent.parent.id

    @category_children_array = Category.where(ancestry: child.ancestry)
    @child_array             = []
    @child_array << child.name
    @child_array << child.id

    @category_grandchildren_array = Category.where(ancestry: grandchild.ancestry)
    @grandchild_array             = []
    @grandchild_array << grandchild.name
    @grandchild_array << grandchild.id
  end

  def update
    grandchild                    = @item.category
    child                         = grandchild.parent
    @category_parent_array        = Category.where(ancestry: nil)
    @category_children_array      = Category.where(ancestry: child.ancestry)
    @category_grandchildren_array = Category.where(ancestry: grandchild.ancestry)
    if item_params[:images_attributes].nil?
      flash.now[:alert] = "更新できませんでした 【画像を１枚以上入れてください】"
      render :edit
    else
      exit_ids = []
      item_params[:images_attributes].each do |a, b|
        exit_ids << item_params[:images_attributes].dig(:"#{a}", :id).to_i
      end
      ids        = Image.where(item_id: params[:id]).map { |image| image.id }
      delete__db = ids - exit_ids
      Image.where(id: delete__db).destroy_all
      @item.touch
      if @item.update(item_params)
        redirect_to item_path
      else
        flash.now[:alert] = '更新できませんでした'
        render :edit
      end
    end
  end


  def show
    @image             = Image.where(item_id: @item)
    @item_grandchildId = Category.find(@item.category_id)
    @item_childId      = @item_grandchildId.parent
    @item_parentId     = Category.find(@item_childId.ancestry)
    @condition         = Condition.find(@item.condition_id)
    @shipping_cost     = ShippingCost.find(@item.shipping_cost_id)
    @shipping_time     = ShippingTime.find(@item.shipping_time_id)
    @prefecture        = Prefecture.find(@item.prefecture_id)
    @price             = @item.price
    gon.imageId        = @image.ids
  end

  def destroy
    if @item.destroy
      flash[:notice] = '商品を削除しました。'
      redirect_to user_path(current_user)
    else
      flash[:alert] = '削除に失敗しました。'
      redirect_to user_path(current_user)
    end
  end

  def search_child
    respond_to do |format|
      format.html
      format.json do
        @children = Category.find(params[:parent_id]).children
        return @children
      end
    end
  end

  def search_grandchild
    respond_to do |format|
      format.html
      format.json do
        @grandchildren = Category.find(params[:child_id]).children
        return @grandchildren
      end
    end
  end

  def select_category_index
    # カテゴリ名を取得するために@categoryにレコードをとってくる
    @category = Category.find_by(id: params[:id])

    # 親カテゴリーを選択していた場合の処理
    if @category.ancestry == nil
      # Categoryモデル内の親カテゴリーに紐づく孫カテゴリーのidを取得
      category = Category.find_by(id: params[:id]).indirect_ids
      # 孫カテゴリーに該当するitemsテーブルのレコードを入れるようの配列を用意
      @items = []
      # find_itemメソッドで処理
      find_item(category)

      # 孫カテゴリーを選択していた場合の処理
    elsif @category.ancestry.include?("/")
      # Categoryモデル内の親カテゴリーに紐づく孫カテゴリーのidを取得
      @items = Item.where(category_id: params[:id])

      # 子カテゴリーを選択していた場合の処理
    else
      category = Category.find_by(id: params[:id]).child_ids
      # 孫カテゴリーに該当するitemsテーブルのレコードを入れるようの配列を用意
      @items = []
      # find_itemメソッドで処理
      find_item(category)
    end
  end

  def confirm
    @image    = @item.images
    @adresses = Address.find(current_user.id)
    # 売り切れ商品に直接パス指定され購入されそうになった時用
    if @item.buyer_id.present?
      flash[:notice] = 'その商品は売り切れです'
      redirect_to '/'
    end
    # すでにクレジットカードが登録しているか？
    if @card.present?
      # 登録している場合,PAY.JPからカード情報を取得する
      # PAY.JPの秘密鍵をセットする。
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      # PAY.JPから顧客情報を取得する。
      customer = Payjp::Customer.retrieve(@card.payjp_id)
      # PAY.JPの顧客情報から、デフォルトで使うクレジットカードを取得する。
      @card_info = customer.cards.retrieve(customer.default_card)
      # クレジットカード情報から表示させたい情報を定義する。
      # クレジットカードの画像を表示するために、カード会社を取得
      @card_brand = @card_info.brand
      # クレジットカードの有効期限を取得

      # クレジットカード会社を取得したので、カード会社の画像をviewに表示させるため、ファイルを指定する。
      case @card_brand
        when 'Visa'
          # 例えば、Pay.jpからとってきたカード情報の、ブランドが"Visa"だった場合は返り値として(画像として登録されている)Visa.pngを返す
          @card_image = 'visa.gif'
        when 'JCB'
          @card_image = 'jcb.gif'
        when 'MasterCard'
          @card_image = 'master.png'
        when 'American Express'
          @card_image = 'amex.gif'
        when 'Diners Club'
          @card_image = 'diners.gif'
        when 'Discover'
          @card_image = 'discover.gif'
      end

      #  viewの記述を簡略化
      ## 有効期限'月'を定義
      @exp_month = @card_info.exp_month.to_s
      ## 有効期限'年'を定義
      @exp_year = @card_info.exp_year.to_s.slice(2, 3)
    end
  end

  private

  def login
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def item_params
    params.require(:item).permit(:image_ids, :name, :price, :description, :condition_id, :shipping_cost_id, :shipping_time_id, :prefecture_id, :category_id, :brand, :buyer_id, :seller_id, images_attributes: [:image, :_destroy, :id]).merge(seller_id: current_user.id, category_id: params[:category_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def show_all_instance
    @user                = User.find(@item.seller_id)
    @images              = Image.where(item_id: params[:id])
    @images_first        = Image.where(item_id: params[:id]).first
    @category_id         = @item.category_id
    @category_parent     = Category.find(@category_id).parent.parent
    @category_child      = Category.find(@category_id).parent
    @category_grandchild = Category.find(@category_id)
  end

  def find_item(category)
    category.each do |id|
      item_array = Item.includes(:images).where(category_id: id)
      # find_by()メソッドで該当のレコードがなかった場合、itemオブジェクトに空の配列を入れないようにするための処理
      if item_array.present?
        item_array.each do |item|
          if item.present?
            # find_by()メソッドで該当のレコードが見つかった場合、@item配列オブジェクトにそのレコードを追加する
            @items.push(item)
          end
        end
      end
    end
  end

  def index_category_set
    array = [1, 2, 3, 4]
    for num in array do
      search_anc = Category.where('ancestry LIKE(?)', "#{num}/%")
      ids        = []
      search_anc.each do |i|
        ids << i[:id]
      end
      @items = Item.where(category_id: ids).order("id DESC").limit(10)
      instance_variable_set("@cat_no#{num}", @items)
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_card
    @card = CreditCard.where(user_id: current_user.id).first if CreditCard.where(user_id: current_user.id).present?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/confirm.html.haml
%section.confirm
  = render 'shared/icon'
  .confirm__box
    %h2 購入確認
    .confirm__box__item
      .confirm__box__item-img
        =link_to item_path(@item.id) do
          = image_tag @item.images[0].image.url, size: "100x100"
      .confirm__box__item__info
        .confirm__box__item__info-name
          = @item.name
        .confirm__box__item__info-price
          %span.tax (税込み)
          %span.price
            = "¥#{@item.price}"
    .confirm__box__confirmPrice
      .confirm__box__confirmPrice-title
        支払い金額
      .confirm__box__confirmPrice-price
        = "¥#{@item.price}"

    .confirm__box__confirmPey
      .confirm__box__confirmPey-title
        支払い方法
      .single-container
        %section.credit_card_section
          - if @card.present?
            .container
              .credit_card-info
                -# indexメソッドで定義した@card_imageを呼び出し、画像をcredit_cardsというフォルダを作り、入れておく
                = image_tag "creditcards/#{@card_image}",width:'34',height:'20', alt:'master-card'
                %p.credit_card-info__number
                  = "**** **** **** " + @card_info.last4 #クレジットカードの下４桁を表示
                %p.credit_card-info__period
                = @exp_month + " / " + @exp_year
                = button_to "削除する", credit_card_path(@card), method: :delete, class:"credit_card-info__delete"
          - else
            .new-card
              = link_to new_credit_card_path, class:"new-card-btn" do
                %i.far.fa-credit-card
                登録してください
    .confirm__box__confirmAddress
      %p.title 配送先
      .confirm__box__confirmAddress-inner
        %p.confirm__box__confirmAddress-inner__postcode
          ="〒#{current_user.address.post_code}"
        %p.confirm__box__confirmAddress-inner__address
          = @adresses.prefecture.name
          = current_user.address.city 
          = current_user.address.address
        %p.confirm__box__confirmAddress-inner__buyer
          = current_user.address.destination_name
    .confirm__box__confirmBottom
      %p
        郵便局/コンビニ受取をご希望の方は、購入後に取引画面から受取場所を変更をすることが可能です。
        出品者が発送作業を開始した後は受取場所の変更ができませんので、早めに変更を行ってください。
    .confirm__box__confirmButton
      - if @card.present?
        .button
          = link_to "購入する", buy_credit_card_path(@item.id), method: :get
      - else
        .button_not
          支払い方法を登録してください

app/views/items/index.html.haml
= render 'shared/header'
.MainApp
  .MainApp__Theme
    .MainApp__Theme__Content
      %h2.MainApp__Theme__Content__SubTitle
        %br
        人生を変えるフリマアプリ
      %p.MainApp__Theme__Content__Text
        FURIMAはだれにでもかんたんに出品・購入できる
        %br
        フリマアプリです
      .MainApp__Theme__Content__BTN
        .apple
          = link_to image_tag(src= "http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class: "MainApp__Theme__Content__BTN__Apple"), '#'
        .google
          = link_to image_tag(src="http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class: "MainApp__Theme__Content__BTN__Google"), '#'
    .MainApp__Theme__Picture3"""
  .MainApp__Reason
    %h2.MainApp__Reason__SubTitle
      FURIMAが選ばれる3つの理由
    %ul.MainApp__Reason__Lists
      %li.MainApp__Reason__Lists__List
        .MainApp__Reason__Lists__List__Pict
          %span.MainApp__Reason__Lists__List__Pict__Number 1
          %img{ src: asset_path('pict-reason-01.jpg'), alt: "画像"}
        %h3.MainApp__Reason__Lists__List__Text
          %span 3分
          ですぐに出品
        %p.MainApp__Reason__Lists__List__Description
          スマホで入力するだけで簡単に出品できる！
      %li.MainApp__Reason__Lists__List
        .MainApp__Reason__Lists__List__Pict
          %span.MainApp__Reason__Lists__List__Pict__Number 2
          %img{ src: asset_path('pict-reason-02.jpg'), alt: "画像"}
        %h3.MainApp__Reason__Lists__List__Text
          %span シンプル
          で使いやすい
        %p.MainApp__Reason__Lists__List__Description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.MainApp__Reason__Lists__List
        .MainApp__Reason__Lists__List__Pict
          %span.MainApp__Reason__Lists__List__Pict__Number 3
          %img{ src: asset_path('pict-reason-03.jpg'), alt: "画像"}
        %h3.MainApp__Reason__Lists__List__Text
          手数料
          %span 業界最安
        %p.MainApp__Reason__Lists__List__Description
          最大3%でお得に出品&購入！
  .MainApp__Achievement
    .MainApp__Achievement__Inner
      %h2.MainApp__Achievement__Inner__SubTitle 会員数日本一位
      %p.MainApp__Achievement__Inner__Text
        FURIMAは、フリマアプリで最も人気。
        %br 出品・購入回数も業界最多です！ 
        ほしかったあの商品に出会えるかもしれません。
      .MainApp__Achievement__Inner__BTN
        .apple
          = link_to image_tag(src= "http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class: "MainApp__Achievement__Inner__BTN__Apple"), '#'
        .google
          = link_to image_tag(src="http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class: "MainApp__Achievement__Inner__BTN__Google"), '#'
  .MainApp__Feature
    %h2.MainApp__Feature__Head
      FURIMAの特徴
    .MainApp__Feature__Items
      .MainApp__Feature__Items__Item
        %img{ src: asset_path('icon-01.png'), class:"MainApp__Feature__Items__Item__Img"}
        %h3.MainApp__Feature__Items__Item__SubTitle
          簡単に売り買いできる
        %p.MainApp__Feature__Items__Item__Detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .MainApp__Feature__Items__Item
        %img{ src: asset_path('icon-03.png'), class:"MainApp__Feature__Items__Item__Img"}
        %h3.MainApp__Feature__Items__Item__SubTitle
          売上金は即日振込みに対応
        %p.MainApp__Feature__Items__Item__Detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
      .MainApp__Feature__Items__Item
        %img{ src: asset_path('icon-04.png'), class:"MainApp__Feature__Items__Item__Img"}
        %h3.MainApp__Feature__Items__Item__SubTitle
          様々な支払いに対応
        %p.MainApp__Feature__Items__Item__Detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  .MainApp__Conteiner
    %h2.MainApp__Conteiner__Head
      ピックアップカテゴリー
    .MainApp__Conteiner__PruductBox
      .MainApp__Conteiner__PruductBox__Head
        = link_to "#", class: "MainApp__Conteiner__PruductBox__Head__Link"  do
          %h3.MainApp__Conteiner__PruductBox__Head__Link__Title
            新規投稿
      .MainApp__Conteiner__PruductBox__Lists
        - @items.first(4).each do |item|
          .MainApp__Conteiner__PruductBox__Lists__List
            =link_to item_path(item.id), class: "MainApp__Conteiner__PruductBox__Lists__List__A" do
              .MainApp__Conteiner__PruductBox__Lists__List__A__Img
                -if item.buyer_id.present?
                  .Sold
                    .Sold__Inner
                      SOLD
                = image_tag item.images[0].image.url 
              .MainApp__Conteiner__PruductBox__Lists__List__A__Body
                %h3.MainApp__Conteiner__PruductBox__Lists__List__A__Body__Name
                  = item.name
                .MainApp__Conteiner__PruductBox__Lists__List__A__Body__Details
                  %ul
                    %li
                      = item.price
                    %li
                      .icon
                        = icon('fas', 'star')
                      0 
                  %p
                    （税込）
  .MainApp__Conteiner
    %h2.MainApp__Conteiner__Head
      ピックアップカテゴリー
    .MainApp__Conteiner__PruductBox
      .MainApp__Conteiner__PruductBox__Head
        = link_to '/items/2/select_category_index', class: "MainApp__Conteiner__PruductBox__Head__Link"  do
          %h3.MainApp__Conteiner__PruductBox__Head__Link__Title
            メンズカテゴリー
      .MainApp__Conteiner__PruductBox__Lists
        - @mens.first(4).each do |item|
          .MainApp__Conteiner__PruductBox__Lists__List
            =link_to item_path(item.id), class: "MainApp__Conteiner__PruductBox__Lists__List__A" do
              .MainApp__Conteiner__PruductBox__Lists__List__A__Img
                -if item.buyer_id.present?
                  .Sold
                    .Sold__Inner
                      SOLD
                = image_tag item.images[0].image.url 
              .MainApp__Conteiner__PruductBox__Lists__List__A__Body
                %h3.MainApp__Conteiner__PruductBox__Lists__List__A__Body__Name
                  = item.name
                .MainApp__Conteiner__PruductBox__Lists__List__A__Body__Details
                  %ul
                    %li
                      = item.price
                    %li
                      .icon
                        = icon('fas', 'star')
                      0 
                  %p
                    （税込）
    .MainApp__Conteiner__PruductBox
      .MainApp__Conteiner__PruductBox__Head
        = link_to '/items/1/select_category_index', class: "MainApp__Conteiner__PruductBox__Head__Link"  do
          %h3.MainApp__Conteiner__PruductBox__Head__Link__Title
            レディースカテゴリー
      .MainApp__Conteiner__PruductBox__Lists
        - @ladies.first(4).each do |item|
          .MainApp__Conteiner__PruductBox__Lists__List
            =link_to item_path(item.id), class: "MainApp__Conteiner__PruductBox__Lists__List__A" do
              .MainApp__Conteiner__PruductBox__Lists__List__A__Img
                -if item.buyer_id.present?
                  .Sold
                    .Sold__Inner
                      SOLD
                = image_tag item.images[0].image.url 
              .MainApp__Conteiner__PruductBox__Lists__List__A__Body
                %h3.MainApp__Conteiner__PruductBox__Lists__List__A__Body__Name
                  = item.name
                .MainApp__Conteiner__PruductBox__Lists__List__A__Body__Details
                  %ul
                    %li
                      = item.price
                    %li
                      .icon
                        = icon('fas', 'star')
                      0 
                  %p
                    （税込）
    .MainApp__Conteiner__PruductBox
      .MainApp__Conteiner__PruductBox__Head
        = link_to '/items/1/select_category_index', class: "MainApp__Conteiner__PruductBox__Head__Link"  do
          %h3.MainApp__Conteiner__PruductBox__Head__Link__Title
            ベビー・キッズカテゴリー
      .MainApp__Conteiner__PruductBox__Lists
        - @babies.first(4).each do |item|
          .MainApp__Conteiner__PruductBox__Lists__List
            =link_to item_path(item.id), class: "MainApp__Conteiner__PruductBox__Lists__List__A" do
              .MainApp__Conteiner__PruductBox__Lists__List__A__Img
                -if item.buyer_id.present?
                  .Sold
                    .Sold__Inner
                      SOLD
                = image_tag item.images[0].image.url 
              .MainApp__Conteiner__PruductBox__Lists__List__A__Body
                %h3.MainApp__Conteiner__PruductBox__Lists__List__A__Body__Name
                  = item.name
                .MainApp__Conteiner__PruductBox__Lists__List__A__Body__Details
                  %ul
                    %li
                      = item.price
                    %li
                      .icon
                        = icon('fas', 'star')
                      0 
                  %p
                    （税込）
.Appbanner
  .Appbanner__Inner
    %h2.Appbanner__Inner__Title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.Appbanner__Inner__Text
      今すぐ無料ダウンロード！
    .Appbanner__Inner__BTN
      .apple
        = link_to image_tag(src= "http://furima.tokyo/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class: "Appbanner__Inner__BTN__Apple"), '#'
      .google
        = link_to image_tag(src="http://furima.tokyo/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class: "Appbanner__Inner__BTN__Google"), '#'

= link_to new_item_path, data: {"turbolinks" => false} do
  .purchase-btn
    %span.purchase-btn__text 出品する
    = image_tag "icon_camera.png", class: "purchase-btn__icon"
= render 'shared/footer'

app/views/items/select_category_index.html.haml
= render 'shared/header'
%section.SelectCategoryBody
  .SelectCategoryBody__Title
    -if @category == 0
      %p.SelectCategoryBody__Title--Head すべての商品一覧
    -else
      %p.SelectCategoryBody__Title--Head
        = "#{@category.name}の商品一覧"
      .SelectCategoryBody__ContentsList
        -@items.each do |item|
          .SelectCategoryBody__ContentsList__Content
            .SelectCategoryBody__ContentsList__Content__sold
              -if item.buyer_id.present? 
                .items-box_photo__sold
                  .items-box_photo__sold__inner
                    SOLD
            .SelectCategoryBody__ContentsList__Content__ImageArea
              - item.images.each_with_index do |image, idx|
                - if idx == 0
                  = link_to item_path(item.id) do
                    = image_tag image.image.url, class:"SelectCategoryBody__ContentsList__Content__ImageArea--Img"
                - else
              .SelectCategoryBody__ContentsList__Content__ImageArea--Price
                = "¥ #{item.price}"
            .SelectCategoryBody__ContentsList__Content__TextArea
              = item.name
= render 'shared/footer'

app/views/items/show.html.haml
= render 'shared/header'
= render 'shared/breadcrumbs'
%section.item-show
  .item-show__box
    .item-show__box__title
      %h2
        = @item.name
    .item-show__box__main
      .itemImageArea
        .itemImageArea-select
          = image_tag @image.first.image.url, class: "imageSelect"
        .itemImageArea-sub
          - @image.ids.each do |i|
            .subImage
              = image_tag Image.find(i).image.url, id: "image", class: "subImage__content"
      .item-show__box__main-right
        %table
          %tr
            %th
              出品者
            %td
              = link_to "#" do
                = User.find(@item.seller_id).nickname
          %tr
            %th
              カテゴリー
            %td
              = link_to select_category_index_item_path do
                ＞
                = @item_parentId.name
                %br
              = link_to "/items/#{@item_childId.id}/select_category_index" do
                ＞
                = @item_childId.name
                %br
              = link_to "/items/#{@item_grandchildId.id}/select_category_index" do
                ＞
                = @item_grandchildId.name
          %tr
            %th
              ブランド
            %td
              = link_to "#" do
                = @item.brand
          %tr
            %th
              商品の状態
            %td
              = @condition.name
          %tr
            %th
              配送料の負担
            %td
              = @shipping_cost.name
          %tr
            %th
              配送元地域	
            %td
              = @prefecture.name
          %tr
            %th
              発送日の目安
            %td
              = @shipping_time.name
    .item-show__box__price
      %p
        ¥
        = @price 
        - if @shipping_cost.id == 1
          %span
            (税込)送料込み
        - else
          %span
            (税込)
    .item-show__box__description
      .description-area
        = @item.description
    .item-show__box__button
      - if user_signed_in? && current_user.id == @item.seller_id
        = link_to "商品編集",edit_item_path(@item.id), data: {"turbolinks" => false},class: "button"
        = link_to "削除", item_path(@item.id), method: :delete, class: "deleteview"

       
          
      - else
        .item-show__box__description
          - if user_signed_in?
            - if @item.buyer_id.present? 
              .button_out
                売り切れ
            - else
              %button{type: "submit", class: "button"}
                = link_to "購入画面に進む", confirm_item_path, class: "letter"
          - else
            %button{type: "submit", class: "button_out"}
              = link_to "ログインしてください", new_user_session_path, class: "letter"

= render 'shared/footer'



-# ＜追加実装のコメント部分＞
  -# .item-show__comment__box
  -#   .item-show__comment__box-form
  -#     %from
  -#       %textarea{name: "comment", type: "text",  placeholder: "コメントする", rows: "2", class: "input"}
  -#       %button{type: "submit", class: "button"}
  -#         .letter
  -#           コメントする

app/views/items/update_done.html.haml
%h2 商品情報を更新しました